stages:
  - ansible-lint
  - getHetznerInfo
  - manageServer
  - backupServer
  - restoreServer
ansible-lint:
  stage: ansible-lint    
  only:
    variables:
      - $DO_THIS == null
    changes:
      - ansible-playbooks/*
  image:
    name: cytopia/ansible-lint:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - ansible-lint ansible-playbooks/*
getHetznerInfo:
  stage: getHetznerInfo
  variables:
    API_HETZNER: $API_HETZNER
    DO_THIS: $DO_THIS
  only:
    variables:
      - $DO_THIS =~ /^get */
  trigger:
    include: 'child-pipelines/.gitlab-ci-getHetznerInfo.yml'
    strategy: depend
manageServer:
  stage: manageServer
  variables:
    API_HETZNER: $API_HETZNER
    DO_THIS: $DO_THIS
    SSH_KEY: $SSH_KEY
  only:
    variables:
      - $DO_THIS =~ /^server */
  trigger:
    include: 'child-pipelines/.gitlab-ci-manageServer.yml'
    strategy: depend
