stages:
  - ansible-lint
  - getAllInfo
  - getServer
  - getServerIp
  - createServer
  - deleteServer
  - restartServer
ansible-lint:
  stage: ansible-lint    
  only:
    variables:
      - $DO_THIS == null
    changes:
      - ansible-playbooks/*
  image:
    name: cytopia/ansible-lint:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - ansible-lint ansible-playbooks/*
getAllInfo:
  stage: getAllInfo
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/start.yml
  only:
    variables:
      - $DO_THIS == "get all info"
  #rules:
  #  - if: $CI_COMMIT_TAG
getServer:
  stage: getServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "get info"
getServerIp:
  stage: getServerIp
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/getServerIP.yml
  only:
    variables:
      - $DO_THIS == "get ip"
createServer:
  stage: createServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  before_script:
    - pip3 install hcloud
    - apk add openssh-client
    - ansible-galaxy install geerlingguy.swap
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
  script:
    - ansible-playbook ansible-playbooks/createServer.yml
    - ansible-playbook ansible-playbooks/getServerIP.yml
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook ansible-playbooks/create_swap.yml -i ~/inventory.ini
    #- ansible-playbook ansible-playbooks/create_server_user.yml -i ~/inventory.ini 
    #- ansible-playbook ansible-playbooks/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "create server"
deleteServer:
  stage: deleteServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/destroyServer.yml
    - ansible-playbook ansible-playbooks/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "delete server"
restartServer:
  stage: restartServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/restartServer.yml
  only:
    variables:
      - $DO_THIS == "restart server"
