stages:
  - ansible-lint
  - ansible-job
  - getServer
  - createServer
  - deleteServer
ansible-lint:
  stage: ansible-lint
  image:
    name: cytopia/ansible-lint:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - ansible-lint ansible-playbooks/*
ansible:
  stage: ansible-job
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/start.yml
  only:
    variables:
      - $DO_THIS == "get all info"
  #rules:
  #  - if: $CI_COMMIT_TAG
getServer:
  stage: getServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "get info"
createServer:
  stage: createServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/createServer.yml
    - ansible-playbook ansible-playbooks/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "create server"
deleteServer:
  stage: deleteServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/destroyServer.yml
    - ansible-playbook ansible-playbooks/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "delete server"
