stages:
  - ansible-lint
  - ansible-job
ansible-lint:
  stage: ansible-lint
  image:
    name: cytopia/ansible-lint:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - ansible-lint ansible-playbooks/*
ansible:
  stage: ansible-job
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
  #  - ansible-playbook ansible-playbooks/start.yml
  #rules:
  #  - if: $CI_COMMIT_TAG
