stages:
  - ansible-lint
  - getAllInfo
  - getServer
  - getServerIp
  - createServer
  - deleteServer
  - restartServer
ansible-lint:
  stage: ansible-lint    
  only:
    changes:
      - ansible-playbooks/*
  image:
    name: cytopia/ansible-lint:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - ansible-lint ansible-playbooks/*
getAllInfo:
  stage: getAllInfo
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/start.yml
  only:
    variables:
      - $DO_THIS == "get all info"
  #rules:
  #  - if: $CI_COMMIT_TAG
getServer:
  stage: getServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "get info"
getServerIp:
  stage: getServerIp
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/getServerIP.yml
    - cat ~/inventory.ini
  only:
    variables:
      - $DO_THIS == "get ip"
createServer:
  stage: createServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - mkdir ~/.ssh
    - ls ~/ -Al
    #- echo "$SSH_KEY" > ~/.ssh/id_rsa
    - ansible-playbook ansible-playbooks/createServer.yml
    - ansible-playbook ansible-playbooks/getServerIP.yml
    - ls ~/ -Al
    #- ansible-playbook ansible-playbooks/create_server_user.yml
    #- ansible-playbook ansible-playbooks/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "create server"
deleteServer:
  stage: deleteServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/destroyServer.yml
    - ansible-playbook ansible-playbooks/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "delete server"
restartServer:
  stage: restartServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/restartServer.yml
  only:
    variables:
      - $DO_THIS == "restart server"
