stages:
  - ansible-lint
  - ansible-job

ansible-lint:
  stage: ansible-lint
  image: registry.gitlab.com/imagedb/ansible-lint
  script:
    - ansible-lint ansible-playbooks/server-info.yml


ansible:
  stage: ansible
  image:
    name: renato81/ansible-in-docker
    entrypoint: [""]
  script:
    - ansible-galaxy collection install hetzner.hcloud
    - ansible-playbook ansible-playbooks/server-info.yml
  #rules:
  #  - if: $CI_COMMIT_TAG
