stages:
  - ansible-lint
  - ansible-job
ansible-lint:
  stage: ansible-lint
  image:
    name: cytopia/ansible-lint:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - ansible-lint ansible-playbooks/server-info.yml
ansible:
  stage: ansible-job
  image:
    name: renato81/ansible-in-docker
    entrypoint: [""]
  script:
    - pip3 install pip
    - pip3 install --upgrade pip
    - ansible-playbook ansible-playbooks/server-info.yml
  #rules:
  #  - if: $CI_COMMIT_TAG
