stages:
  - testChildPipeline
  - getAllInfo
  - getServer
  - getServerIp
testChildPipeline:
  stage: testChildPipeline
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - echo "Hi all. this child is working"
getAllInfo:
  stage: getAllInfo
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/getHetznerInfo/getAllInfo.yml
  only:
    variables:
      - $DO_THIS == "get all info"
getServer:
  stage: getServer
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/getHetznerInfo/getServerInfoByName.yml
  only:
    variables:
      - $DO_THIS == "get info"
getServerIp:
  stage: getServerIp
  image:
    name: cytopia/ansible:latest
    entrypoint: [""]
  script:
    - pip3 install hcloud
    - ansible-playbook ansible-playbooks/getHetznerInfo/getServerIP.yml
  only:
    variables:
      - $DO_THIS == "get ip"
