---
- hosts: localhost
  vars:
      api_key: "{{ lookup('env','API_HETZNER') }}"
  collections:
    - hetzner.hcloud
  tasks:
    - name: hetzner servers info
      hetzner.hcloud.hcloud_server_info:
        api_token: "{{ api_key }}"
    - name: Gather hcloud servers infos
      hcloud_server_info:
        api_token: "{{ api_key }}"
      register: output
    - name: Print all the servers gathered infos
      debug:
        var: output.hcloud_server_info
