---
- hosts: localhost
  vars:
      api_key: "{{ lookup('env','API_HETZNER') }}"
      server_name: "{{ lookup('env','CI_PROJECT_NAME') }}"
  collections:
    - hetzner.hcloud
  tasks:
    - name: hetzner servers info
      hetzner.hcloud.hcloud_server:
        api_token: "{{ api_key }}"
- name: Ensure the server is absent (remove if needed)
  hcloud_server:
    api_token: "{{ api_key }}"
    name: my-server
    state: absent
