---
- hosts: localhost
  vars:
      api_key: "{{ lookup('env','API_HETZNER') }}"
  collections:
    - hetzner.hcloud
  tasks:
    - name: hetzner info
      hetzner.hcloud.hcloud_datacenter_info:
        api_token: "{{ api_key }}"
    - name: Gather hcloud datacenter info
      hcloud_datacenter_info:
        api_token: "{{ api_key }}"
      register: output
    - name: Print the gathered info
      debug:
        var: output
