---
- hosts: localhost
  vars:
      api_key: "{{ lookup('env','API_HETZNER') }}"
      server_name: "{{ lookup('env','CI_PROJECT_NAME') }}"
  collections:
    - hetzner.hcloud
  tasks:
    - name: hetzner server info
      hetzner.hcloud.hcloud_server_info:
        api_token: "{{ api_key }}"
    - name: Gather hcloud server info about one server.
      hcloud_server_info:
        api_token: "{{ api_key }}"
        name: "{{ server_name }}"
      register: output
    - name: Set IP as fact
      set_fact: host_ip="{{ output.hcloud_server_info[0].ipv4_address }}"
    - name: Print IP
      debug:
        msg: "{{ host_ip }}"
    - name: Creating a file with content
      copy:
        dest: "~/inventory.ini"
        content: |
          [yourserver]
          "{{ host_ip }}"
    - name: This command will change the working directory to somedir/
      ansible.builtin.shell:
      cmd: YOURSERVER="{{ host_ip }}"
