---
- hosts: localhost
  vars:
      api_key: "{{ lookup('env','API_HETZNER') }}"
      server_name: "{{ lookup('env','CI_PROJECT_NAME') }}"
  collections:
    - hetzner.hcloud
  tasks:
    - name: hetzner server info
      hetzner.hcloud.hcloud_server_info:
        api_token: "{{ api_key }}"
    - name: Gather hcloud server info about one server.
      hcloud_server_info:
        api_token: "{{ api_key }}"
        name: "{{ server_name }}"
      register: output
    - name: Set IP as fact
      set_fact: host_ip="{{ output.hcloud_server_info[0].ipv4_address }}"
    - name: Debug
      debug:
        var: "{{ host_ip }}"
      
